spring:
  application:
    name: account

  r2dbc:
    url: r2dbc:postgresql://${DB_ACCOUNT_HOST:bank-dev-account-db.dev.svc.cluster.local}:${DB_ACCOUNT_PORT:5432}/${DB_ACCOUNT_NAME:account_db}?sslMode=disable
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}

  datasource:
    url: jdbc:postgresql://${DB_ACCOUNT_HOST:bank-dev-account-db.dev.svc.cluster.local}:${DB_ACCOUNT_PORT:5432}/${DB_ACCOUNT_NAME:account_db}?sslMode=disable
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}

  liquibase:
    change-log: classpath:db/changelog/account/db.changelog-master.yaml
    url: jdbc:postgresql://${DB_ACCOUNT_HOST:bank-dev-account-db.dev.svc.cluster.local}:${DB_ACCOUNT_PORT:5432}/${DB_ACCOUNT_NAME:account_db}?sslMode=disable
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: dev,test,default

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak/realms/bank/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_ACCOUNT_SECRET:a2977717-36e6-42bc-862d-06927877298c}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/bank