services:

  consul:
    image: hashicorp/consul:1.20
    container_name: consul
    command: [ "agent","-dev","-ui","-client","0.0.0.0", "-log-level","ERROR" ]
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - bank-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: >
      start-dev --import-realm --http-port=8082 --http-enabled=true 
      --hostname-strict=false 
      --proxy-headers=xforwarded
    env_file: ./env/.env
    volumes:
      - ./env/realm-export.json:/opt/keycloak/data/import/realm.json:ro
      - ./env/keycloak-theme/bank-theme:/opt/keycloak/themes/bank-theme:ro
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bank-network

  account_db:
    image: postgres:17-alpine
    container_name: account-db
    restart: unless-stopped
    env_file: ./env/.env
    environment:
      POSTGRES_DB: ${DB_ACCOUNT_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - account_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

  cash_db:
    image: postgres:17-alpine
    container_name: cash-db
    restart: unless-stopped
    env_file: ./env/.env
    environment:
      POSTGRES_DB: ${DB_CASH_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - cash_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

  notification_db:
    image: postgres:17-alpine
    container_name: notification-db
    restart: unless-stopped
    env_file: ./env/.env
    environment:
      POSTGRES_DB: ${DB_NOTIFICATION_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

  transfer_db:
    image: postgres:17-alpine
    container_name: transfer-db
    restart: unless-stopped
    env_file: ./env/.env
    environment:
      POSTGRES_DB: ${DB_TRANSFER_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - transfer_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

volumes:
  account_db_data:
  cash_db_data:
  notification_db_data:
  transfer_db_data:
  keycloak_data:

networks:
  bank-network:
    driver: bridge