spring:
  application:
    name: transfer

  config:
    import: "optional:consul:${CONSUL_HOST:localhost}:8500"

  r2dbc:
    url: r2dbc:postgresql://${DB_TRANSFER_HOST:localhost}:${DB_TRANSFER_PORT:5434}/${DB_TRANSFER_NAME:transfer_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  datasource:
    url: jdbc:postgresql://${DB_TRANSFER_HOST:localhost}:${DB_TRANSFER_PORT:5434}/${DB_TRANSFER_NAME:transfer_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/transfer/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA:public}
    url: jdbc:postgresql://${DB_TRANSFER_HOST:localhost}:${DB_TRANSFER_PORT:5434}/${DB_TRANSFER_NAME:transfer_db}
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: dev,test,default

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.local/realms/bank/protocol/openid-connect/certs
          issuer-uri: http://keycloak.local/realms/bank
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_TRANSFER_SECRET:c4999939-58e8-64de-a84f-2814909941ae}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak.local/realms/bank

server:
  port: ${SPRING_TRANSFER_PORT:8086}