spring:
  application:
    name: notification

  config:
    import: "optional:consul:${CONSUL_HOST:localhost}:8500"

  r2dbc:
    url: r2dbc:postgresql://${DB_NOTIFICATION_HOST:localhost}:${DB_NOTIFICATION_PORT:5435}/${DB_NOTIFICATION_NAME:notification_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  datasource:
    url: jdbc:postgresql://${DB_NOTIFICATION_HOST:localhost}:${DB_NOTIFICATION_PORT:5435}/${DB_NOTIFICATION_NAME:notification_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/notification/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA:public}
    url: jdbc:postgresql://${DB_NOTIFICATION_HOST:localhost}:${DB_NOTIFICATION_PORT:5435}/${DB_NOTIFICATION_NAME:notification_db}
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: dev,test,default

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.local/realms/bank/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_NOTIFICATION_SECRET:d5000040-69f9-75ef-b950-3925010052bf}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak.local/realms/bank

server:
  port: ${SPRING_NOTIFICATION_PORT:8085}