spring:
  application:
    name: cash

  r2dbc:
    url: r2dbc:postgresql://${DB_CASH_HOST:localhost}:${DB_CASH_PORT:5432}/${DB_CASH_NAME:cash_db}?sslMode=disable
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}

  datasource:
    url: jdbc:postgresql://${DB_CASH_HOST:localhost}:${DB_CASH_PORT:5432}/${DB_CASH_NAME:cash_db}?sslMode=disable
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}

  liquibase:
    change-log: classpath:db/changelog/cash/db.changelog-master.yaml
    url: jdbc:postgresql://${DB_CASH_HOST:localhost}:${DB_CASH_PORT:5432}/${DB_CASH_NAME:cash_db}?sslMode=disable
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: dev,test,default

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak/realms/bank/protocol/openid-connect/certs
          issuer-uri: http://keycloak/realms/bank
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_CASH_SECRET:b3888828-47f7-53cd-973e-17038988309d}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/bank