spring:
  application:
    name: cash

  config:
    import: "optional:consul:${CONSUL_HOST:localhost}:8500"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
      config:
        enabled: true
        format: yaml
        prefixes: [ config ]
        defaultContext: application
        watch:
          enabled: true
          delay: 1000

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_CASH_PORT:5434}/${DB_CASH_NAME:cash_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_CASH_PORT:5434}/${DB_CASH_NAME:cash_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/cash/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA:public}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_CASH_PORT:5434}/${DB_CASH_NAME:cash_db}
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: dev,test,default

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:8082/realms/${KEYCLOAK_REALM:bank}/protocol/openid-connect/certs
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8082/realms/${KEYCLOAK_REALM:bank}
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_CASH_SECRET:b3888828-47f7-53cd-973e-17038988309d}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8082}/realms/${KEYCLOAK_REALM:bank}

server:
  port: ${SPRING_CASH_PORT:8084}