apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-db.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}