apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    app: {{ include "postgres-db.name" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port | default 5432 }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "postgres-db.name" . }}