apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-db.fullname" . }}
spec:
  serviceName: {{ include "postgres-db.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-db.name" . }}
    spec:
      containers:
        - name: postgres
          image: "postgres:17-alpine"
          envFrom:
            - secretRef:
                name: {{ include "postgres-db.fullname" . }}-secret
          volumeMounts:
              - name: data
                mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}