apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
data:
  realm.json: |-
    {{ .Files.Get "env/realm-export.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme-bank
data:
  theme.properties: |-
    {{ .Files.Get "env/keycloak-theme/bank-theme/theme.properties" | indent 4 }}

  login.ftl: |-
    {{ .Files.Get "env/keycloak-theme/bank-theme/login/login.ftl" | indent 4 }}

  register.ftl: |-
    {{ .Files.Get "env/keycloak-theme/bank-theme/login/register.ftl" | indent 4 }}

  style.css: |-
    {{ .Files.Get "env/keycloak-theme/bank-theme/login/resources/css/style.css" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: dev
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  realm.json: |
    {
      "realm": "bank",
      "enabled": true,
      "clients": [
        {
          "clientId": "bank-client",
          "enabled": true,
          "protocol": "openid-connect",
          "redirectUris": ["*"],
          "publicClient": true
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "password"
            }
          ]
        }
      ]
    }
