# keycloak-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: dev
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak123
  POSTGRES_DB: keycloak
