# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-bank-common-secrets
type: Opaque
stringData:
  DB_PASSWORD: "bank_password"

  KEYCLOAK_FRONT_UI_SECRET: "90bd600c-7781-4435-961e-1f5139265f7c"
  KEYCLOAK_GATEWAY_SECRET: "g7777777-8888-9999-aaaa-bbbbccccdddd"
  KEYCLOAK_ACCOUNT_SECRET: "a2977717-36e6-42bc-862d-06927877298c"
  KEYCLOAK_CASH_SECRET: "b3888828-47f7-53cd-973e-17038988309d"
  KEYCLOAK_NOTIFICATION_SECRET: "d5000040-69f9-75ef-b950-3925010052bf"
  KEYCLOAK_TRANSFER_SECRET: "c4999939-58e8-64de-a84f-2814909941ae"

  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"

  POSTGRES_USER: "bank_admin"
  POSTGRES_PASSWORD: "bank_password"
  POSTGRES_DB: keycloak
