spring:
  application:
    name: template
    notifications:
      url: ${NOTIFICATIONS_HOST:http://notifications/api/v1/notifications}
    date: yyyy-MM-dd HH:mm:ss
  config:
    import: "optional:consul:${CONSUL_HOST:localhost}:8500"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        health-check-path: /actuator/health/readiness
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
      config:
        enabled: true
        prefixes: [ config ]
        defaultContext: application

  resilience:
    instance-name: "default"
    sliding-window-size: 10
    failure-rate-threshold: 50
    wait-duration-in-open-state: 10
    permitted-number-of-calls-in-half-open-state: 3

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    default-schema: ${DB_SCHEMA:public}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    user: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    contexts: default

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:keycloak}:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/bank-realm

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ""
  otlp:
    tracing:
      endpoint: ""

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10