spring:
  application:
    name: chassis-template
    notification:
      url: ${NOTIFICATION_URL:http://notification/notification}
    gateway:
      host: ${GATEWAY_HOST:http://gateway}
    date: yyyy-MM-dd HH:mm:ss
    fixed_write_delay: 5000
    fixed_clean_delay: 50000

  cloud:
    loadbalancer:
      enabled: false

  resilience:
    instanceName: ${spring.application.name}
    sliding-window-size: 10
    failure-rate-threshold: 50
    wait-duration-in-open-state: 10
    permitted-number-of-calls-in-half-open-state: 3

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db}?sslMode=disable
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db}?sslMode=disable
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    default-schema: ${DB_SCHEMA:public}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db}?sslMode=disable
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: default

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8082}/realms/${KEYCLOAK_REALM:bank}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8082}/realms/${KEYCLOAK_REALM:bank}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

server:
  port: 8080