apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ui-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: my-bank
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8080